// src/models/Notification.model.js
//
// A message delivered to a user - primarily generated when an Alert
// fires, but generic enough to support other notification types later
// without a schema change. References User (required) and Alert
// (optional - only set for alert-driven notifications).

'use strict';

const mongoose = require('mongoose');

const TYPE_VALUES = ['price_drop', 'back_in_stock', 'system'];

const notificationSchema = new mongoose.Schema({
    userId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'User',
        required: true,
    },
    // Only set when this notification was generated by an Alert firing.
    alertId: {
        type: mongoose.Schema.Types.ObjectId,
        ref: 'Alert',
        default: null,
    },
    type: {
        type: String,
        enum: TYPE_VALUES,
        required: true,
    },
    title: {
        type: String,
        required: true,
        trim: true,
    },
    message: {
        type: String,
        required: true,
        trim: true,
    },
    // Loose payload for frontend deep-linking, e.g. { productId, price }.
    // Deliberately Mixed - shape varies per notification type, and new
    // types shouldn't require a schema migration.
    data: {
        type: mongoose.Schema.Types.Mixed,
        default: {},
    },
    isRead: {
        type: Boolean,
        default: false,
    },
    readAt: {
        type: Date,
        default: null,
    },
}, {
    timestamps: true, // createdAt = when the notification was generated
});

// Matches the two real query patterns: unread notifications for a badge
// count, and the full list newest-first.
notificationSchema.index({ userId: 1, isRead: 1, createdAt: -1 });

const Notification = mongoose.model('Notification', notificationSchema);

module.exports = Notification;
module.exports.TYPE_VALUES = TYPE_VALUES;